# Numpy

In [13]:
import numpy as np

In [2]:
my_lst = [1,3,4,5,6]
arr = np.array(my_lst)
print(arr)

[1 3 4 5 6]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(5,)

In [8]:
# Multidimensional array 
l1 = [1,3,4,5]
l3 = [3,4,5,6]
l4 = [4,5,6,7]
arr = np.array([l1,l3,l4])
print(arr)

[[1 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [10]:
arr.shape

(3, 4)

In [12]:
arr.reshape(1,12)


array([[1, 3, 4, 5, 3, 4, 5, 6, 4, 5, 6, 7]])

 Indexing

In [15]:
# Accessing the array elements
arr[1][3]

6

In [16]:
print(arr)

[[1 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [18]:
arr[1:,2:]

array([[5, 6],
       [6, 7]])

In [19]:
arr[:,:]

array([[1, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [20]:
arr[0:3,1:3]

array([[3, 4],
       [4, 5],
       [5, 6]])

In [22]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr = np.arange(0, 10, 1.5, dtype = int)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [29]:
arr[3:] = 100
arr

array([  0,   1,   2, 100, 100, 100, 100])

In [30]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [31]:
arr1 = arr.copy()

Miscellaneous

In [32]:
val = 2
arr > 2

array([False, False, False,  True,  True,  True,  True])

In [33]:
arr*2

array([  0,   2,   4, 200, 200, 200, 200])

In [34]:
arr%2

array([0, 1, 0, 0, 0, 0, 0], dtype=int32)

In [35]:
arr[arr>2]

array([100, 100, 100, 100])

In [36]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [37]:
arr*arr1

array([    0,     1,     4, 10000, 10000, 10000, 10000])

In [39]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Random distribution

In [40]:
np.random.rand(3,5)

array([[0.55716193, 0.32762034, 0.34268711, 0.50270384, 0.25647873],
       [0.10343255, 0.28497502, 0.56393716, 0.58422131, 0.75444869],
       [0.7038695 , 0.61351953, 0.64969478, 0.07196709, 0.03881173]])

In [46]:
arr_ex = np.random.randn(4,4) # returns sample from standard normal distribution
arr_ex

array([[ 0.4731902 , -0.4402219 ,  0.55299389, -0.70292704],
       [ 0.00887772,  0.9369878 , -0.84227782, -0.15568677],
       [-1.51304678,  0.62789208, -1.67641738, -1.11391167],
       [ 1.68796071, -2.95889273, -1.59883697,  0.23250572]])

In [59]:
import seaborn as sns
import pandas as pd
sns.displot(pd.DataFrame(arr_ex.reshape(16,1)))

In [54]:
np.random.randint(0,10,10).reshape(2,5)

array([[7, 7, 3, 1, 8],
       [4, 0, 0, 0, 3]])

In [56]:
np.random.random_sample((1,5))

array([[0.27138785, 0.50326881, 0.97475012, 0.91518788, 0.48301075]])