In [1]:
import numpy as np

In [ ]:
np_array = np.array([i for i in range(100000)])

np_array += 5

for i in range(10):
  print(np_array[i])

Numpy Arrays


In [4]:
#list
list1 = [1,3,4,5,6]
print(list1)
type(list1)

[1, 3, 4, 5, 6]


list

In [6]:
# CREATING A 1D ARRAY
np_array = np.array([1,3,4,5,6])
print(np_array)
type(np_array)
np_array.shape

[1 3 4 5 6]


(5,)

In [8]:
#CREATING A 2D ARRAY
b = np.array([(1,3,4),(4,5,6),(7,8,9)])
print(b)
b.shape

[[1 3 4]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [9]:
c = np.array([1,3,4],dtype=float)
print(c)

[1. 3. 4.]


Inital Placeholders in numpy arrays

In [10]:
# CREATE NUMPY ARRAY OF ZEROS
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#NUMPY ARRAY OF ONES
y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# ARRAY OF PARTICULAR VALUE
z = np.full((3,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [14]:
# IDENTITY MATRIX
a = np.eye(3) 
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# ARRAY WITH RANDOM VALUES
b = np.random.random((3,4))
print(b)

[[0.16927117 0.55997889 0.64525496 0.41683647]
 [0.42582788 0.57403837 0.55581489 0.41625029]
 [0.47787195 0.14436423 0.14906088 0.04198641]]


In [18]:
# ARRAY WITH RANDOM VALUES (INTEGERS)
b = np.random.randint(10,100,(3,3))
print(b)

[[39 85 39]
 [83 49 64]
 [84 54 94]]


In [23]:
# ARRAY OF EVENLY SPACED VALUES ---> SPECIFYING THE NUMBER OF VALUES REQUIRED
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [25]:
# ARRAY OF EVENLY SPACED VALUES ---> SPECIFYING THE STEP
d = np.arange(10,30,5)
print(d)

[10 15 20 25]


In [26]:
# CONVERTING LIST TO NUMPY ARRAY
ls = [1,34,5,6,8]
npArray = np.asarray(ls)
print(npArray)

[ 1 34  5  6  8]


Analyzing a numpy array

In [31]:
c = np.random.randint(10,90,(5,5))
print(c)
print(c.shape)
print(c.ndim)
#no. of elements
print(c.size)
#datatype
print(c.dtype)

[[56 55 34 44 79]
 [19 75 53 59 53]
 [83 28 63 50 69]
 [22 48 74 20 50]
 [72 40 16 77 88]]
(5, 5)
2
25
int64


**Mathematical operations on a nparray**

In [32]:
#list concatenation
ls1 = [1,3,4]
ls3 = [3,4,5,6]
print(ls1 + ls3)

[1, 3, 4, 3, 4, 5, 6]


In [33]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,30,(3,3))
print(a)
print(b)

[[4 6 8]
 [3 1 5]
 [6 5 5]]
[[ 2  1 13]
 [12 11 27]
 [10 28 17]]


In [ ]:
#operation on elements
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
# or
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

Array Manipulation

In [38]:
# transpose
print(a)
trans = np.transpose(a)
print(trans)
#or
trans3 = a.T
print(trans3)

[[4 6 8]
 [3 1 5]
 [6 5 5]]
[[4 3 6]
 [6 1 5]
 [8 5 5]]
[[4 3 6]
 [6 1 5]
 [8 5 5]]


In [41]:
# reshape an array
a = np.random.randint(0,10,(3,4))
print(a)
b = a.reshape(6,2)
print(b)

[[8 7 8 6]
 [6 1 0 9]
 [9 1 4 6]]
[[8 7]
 [8 6]
 [6 1]
 [0 9]
 [9 1]
 [4 6]]
